### ISSUE TITLE
Errors in cauldron-1.7.10-1.1388.1.0-server

### ISSUE THREAD

**Issue by jojuniori** [FabioZumbi12/PixelVip#15]
### java 8

Too many Warns

```
[03:16:06 WARN]: [PixelVip] Task #366070 for PixelVip v2.0.1 generated an except
ion
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_151]
        at br.net.fabiozumbi12.PixelVip.PVConfig$8.run(PVConfig.java:671) ~[?:?]

        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java
:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.
10-1.1388.1.0]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

```
[03:17:06 WARN]: [PixelVip] Task #366872 for PixelVip v2.0.1 generated an except
ion
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_151]
        at br.net.fabiozumbi12.PixelVip.PVConfig$8.run(PVConfig.java:671) ~[?:?]

        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java
:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.
10-1.1388.1.0]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

```
[03:21:06 WARN]: [PixelVip] Task #364691 for PixelVip v2.0.1 generated an except
ion
java.lang.NullPointerException
```

```
[03:21:08 WARN]: [PixelVip] Task #369262 for PixelVip v2.0.1 generated an except
ion
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_151]
        at br.net.fabiozumbi12.PixelVip.PVConfig$8.run(PVConfig.java:671) ~[?:?]

        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java
:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.
10-1.1388.1.0]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

```
[03:22:09 WARN]: [PixelVip] Task #370030 for PixelVip v2.0.1 generated an except
ion
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_151]
        at br.net.fabiozumbi12.PixelVip.PVConfig$8.run(PVConfig.java:671) ~[?:?]

        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java
:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.
10-1.1388.1.0]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by FabioZumbi12** [comment]
2.0.1 is outdated, download the latest: https://www.spigotmc.org/resources/pixelvip.30438/

**Comment by jojuniori** [comment]
I upgrade and here had new warn
```
[03:43:21 WARN]: [PixelVip] Task #93 for PixelVip v2.0.3 generated an exception
java.lang.NullPointerException
        at br.net.fabiozumbi12.PixelVip.PixelVip.lambda$onPlayerJoin$3(PixelVip.
java:203) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java
:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.
10-1.1388.1.0]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by jojuniori** [comment]
and commands doesn't work anymore

![](http://qiniu.moem.cc/cache/Snipaste_2018-04-25_04-03-52.png)

**Comment by FabioZumbi12** [comment]
This is related to plugin dont load on server start. Check the logs on server starting to get the correct logs for this error.

**Comment by jojuniori** [comment]
oh i saw it

```
[04:53:06] [Server thread/INFO]: [PixelVip] Enabling PixelVip v2.0.3
[04:53:06] [Server thread/INFO]: PixelVip: [Init config module...]
[04:53:06] [Server thread/INFO]: PixelVip: [Init utils module...]
[04:53:06] [Server thread/ERROR]: Error occurred while enabling PixelVip v2.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at br.net.fabiozumbi12.PixelVip.PixelVip.onEnable(PixelVip.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by jojuniori** [comment]
_(:з」∠)_ I upgrade to "PixelVip-2.0.3-b41-Universal.jar" then got the same problem

```
[05:08:15] [Server thread/INFO]: [PixelVip] Enabling PixelVip v2.0.3
[05:08:15] [Server thread/INFO]: PixelVip: [Init config module...]
[05:08:15] [Server thread/INFO]: PixelVip: [Init utils module...]
[05:08:15] [Server thread/ERROR]: Error occurred while enabling PixelVip v2.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.onEnable(PixelVip.java:111) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by FabioZumbi12** [comment]
This error its for non spigot servers. Try the build 42 from jenkins where i try to fix this.

**Comment by jojuniori** [comment]
Thank you very much for fix that, the plugin can enabled now.
When I used command "addvip" still will warn:

```
[05:50:09] [Server thread/WARN]: Unexpected exception while parsing console command "addvip JoJun VIP 30"
org.bukkit.command.CommandException: Unhandled exception executing command 'addvip' in plugin PixelVip v2.0.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:472) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.Essentials.getUser(Ljava/util/UUID;)Lcom/earth2me/essentials/User;
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.changeVipKit(PVConfig.java:637) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.setActive(PVConfig.java:589) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.enableVip(PVConfig.java:521) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:412) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	... 8 more
```

But it doesn't affect move the player to the VIP group.
Thanks again.

**Comment by FabioZumbi12** [comment]
Cool! That other war is because an old version of essentials plugin. Updating may slove this problem.
