### ISSUE TITLE
[bug] Arquivo config.yml reseta toda vez que reinicio o server

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/PixelVip#19]
Platform: Debian 9
Java 8
Mysql

Jar version: PixelVip-2.0.4-b47-Universal.jar

Minecraft version: Spigot 1.13

Edito o arquivo de configuração ele sempre volta ao padrão

obs: comecei a usar o seu plugin nesta verão atual, pois vi que você é o desenvolvedor e como você da muito suporte migrei o plugin de VIP.

**Comment by FabioZumbi12** [comment]
Opa, bem vindo ao pixelvip xD
Eh alguma config que vc ta fazendo de errado que faz ele regenerar toda hora. O log do console vai dizer onde eh certinho.

**Comment by eltonnikecasa** [comment]
Ja editei de varias formas. Ate edições minimas. O console nao da mensagem de erro.

**Comment by eltonnikecasa** [comment]
Tudo que aparece no console, falando de PixelVIP:

[11:19:23] [Server thread/INFO]: [PixelVip] Enabling PixelVip v2.0.4
[11:19:23] [Server thread/INFO]: PixelVip: [Init config module...][m
[11:19:23] [Server thread/INFO]: PixelVip: [Init utils module...][m
[11:19:23] [Server thread/INFO]: PixelVip: [Init essentials module...][m
[11:19:23] [Server thread/INFO]: PixelVip: [Essentials found. Hooked!][m
[11:19:23] [Server thread/INFO]: PixelVip: [Init economy module...][m
[11:19:23] [Server thread/INFO]: PixelVip: [-> Vault found. Hooked.][m
[11:19:23] [Server thread/INFO]: PixelVip: [Init commands module...][m
[11:19:23] [Server thread/INFO]: PixelVip: [Init scheduler module...][m
[11:19:23] [Server thread/INFO]: PixelVip: [Reloading tasks...][m
[11:19:23] [Server thread/INFO]: PixelVip: [-> Task started][m
[11:19:23] [Server thread/INFO]: PixelVip: [-> PlaceHolderAPI found. Hooked.][m
[11:19:23] [Server thread/INFO]: PixelVip: [[0;33;22mWe have 0 active Vips on file[m][m
[11:19:23] [Server thread/INFO]: PixelVip: [[0;32;1m[21mPixelVip enabled![m][m

**Comment by eltonnikecasa** [comment]
comando /darvip

[00:23:56 INFO]: Elton_Nike_Casa issued server command: /darvip Elton_Nike_Casa vip1 10
[00:23:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'darvip' in plugin PixelVip v2.0.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:382) ~[?:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
        ... 15 more

**Comment by eltonnikecasa** [comment]
SilkSpawners desatualizado, tive que baixar no Jenkins deles pra pegar a versão mais nova. Ai parou de resetar o config. Talvez se tirar aquela linha 115, '2': silk give {p} iron_golem 2 , do arquivo de configuração padrão para não acontecer com outras pessoas.

Desculpe pelo incomodo.

**Comment by eltonnikecasa** [comment]
SilkSpawners talvez agora até seja desnecessário o minecraft 1.13 está gerando os spawners normalmente.
/give {p} spawner:100 2
