### ISSUE TITLE
[bug] comando /darvip

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/PixelVip#22]
Platform: Debian 9
Java 8
Mysql

Jar version: PixelVip-2.0.4-b47-Universal.jar

Minecraft version: Spigot 1.13

Descrição:
Não consigo dar vip para o jogador se ele estiver online, com comando /darvip e /givevip.
Se o jogador estiver offline consigo dar o vip, mais os itens não vem quando ele entra, mesmo estando queueCmdsForOfflinePlayers: true.

Log:
[10:05:53] [Server thread/WARN]: Unexpected exception while parsing console command "darvip teste vipd 10"
org.bukkit.command.CommandException: Unhandled exception executing command 'darvip' in plugin PixelVip v2.0.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:679) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at net.minecraft.server.v1_13_R1.DedicatedServer.aW(DedicatedServer.java:453) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:412) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:382) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	... 8 more

**Comment by eltonnikecasa** [comment]
Uma correção o queueCmdsForOfflinePlayers: true esta ok. É só o problema de não conseguir darvip pra player online

**Comment by eltonnikecasa** [comment]
Resolvido na versao b48
