### ISSUE TITLE
i have a 'NullPointerException' error report ,when i use the addvip command;

### ISSUE THREAD

**Issue by mcpanglei** [FabioZumbi12/PixelVip#23]
[20:43:09 INFO]: mcpanglei issued server command: /givevip mcpanglei vip3 1
[20:43:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'givevip' in plugin PixelVip v2.0.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-273]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-273]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1767) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1571) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-273]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[patched_1.13.1.jar:git-Paper-273]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.13.1.jar:git-Paper-273]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:382) ~[?:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-273]
        ... 15 more

**Comment by FabioZumbi12** [comment]
Try the latest dev build from our jenkins
