### ISSUE TITLE
error..

### ISSUE THREAD

**Issue by shuiqing2046** [FabioZumbi12/PixelVip#26]
[16:04:11] [Server thread/INFO]: Angel issued server command: /addvip allens VIP9 10m
[16:04:24] [Server thread/INFO]: Angel issued server command: /addvip allens VIP9 1
[16:04:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'addvip' in plugin PixelVip v2.0.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1766) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1570) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:382) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	... 15 more
[16:05:20] [Server thread/INFO]: Angel issued server command: /addvip allens VIP 1
[16:05:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'addvip' in plugin PixelVip v2.0.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1766) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1570) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:382) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.13.2-b444.jar:git-Paper-444]
	... 15 more

**Comment by FabioZumbi12** [comment]
Its fixed on the latest dev build version from our jenkins
