### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by bertek41** [FabioZumbi12/PixelVip#3]
Spigot 1.8.8 Java 8 Errors:
`[21:30:53] [Server thread/ERROR]: Could not load 'plugins/PixelVip-Spigot-1.0.5-b95.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `br.net.fabiozumbi12.PixelVip-Spigot.PixelVip-Spigot'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.PixelVip-Spigot.PixelVip-Spigot
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	... 7 more`

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build: http://158.69.121.149:8080/job/PixelVip/
