### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by newbie029** [FabioZumbi12/PixelVip#30]
PixelVIP Build 50 on PaperSpigot 1.12.2 Latest Build

Can you add option to useSSL=false on the config please?

Also fix this mysql bug, I back using build 47 everything works

[05:06:22 INFO]: [PixelVip] Init config module...
[05:06:23 WARN]: Tue Jan 29 05:06:23 SGT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[05:06:23 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'null varchar(128), col_nick varchar(128))' at line 1
[05:06:23 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:06:23 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:06:23 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:06:23 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:06:23 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:06:23 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
[05:06:23 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[05:06:23 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[05:06:23 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[05:06:23 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[05:06:23 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[05:06:23 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[05:06:23 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[05:06:23 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[05:06:23 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[05:06:23 WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[05:06:23 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[05:06:23 WARN]: at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.<init>(PVDataMysql.java:135)
[05:06:23 WARN]: at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.reloadVips(PVConfig.java:262)
[05:06:23 WARN]: at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.<init>(PVConfig.java:202)
[05:06:23 WARN]: at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.onEnable(PixelVip.java:119)
[05:06:23 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:06:23 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[05:06:23 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:06:23 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[05:06:23 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[05:06:23 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[05:06:23 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[05:06:23 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[05:06:23 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[05:06:23 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[05:06:23 WARN]: at java.lang.Thread.run(Thread.java:748)
[05:06:23 INFO]: [PixelVip] Database set back to file!
[05:06:23 INFO]: [PixelVip] Reloading config module...
[05:06:23 INFO]: [PixelVip] Reloading tasks...
[05:06:23 INFO]: [PixelVip] -> Task started
[05:06:23 ERROR]: Error occurred while enabling PixelVip v3.0.0 (Is it up to date?)
java.lang.NullPointerException: null
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.reloadCmd(PixelVip.java:88) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.setError(PVDataMysql.java:164) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.<init>(PVDataMysql.java:149) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.reloadVips(PVConfig.java:262) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.<init>(PVConfig.java:202) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.onEnable(PixelVip.java:119) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1592]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[05:06:23 INFO]: [PixelVip] Disabling PixelVip v3.0.0
[05:06:23 ERROR]: Error occurred while disabling PixelVip v3.0.0 (Is it up to date?)
java.lang.NullPointerException: null
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.onDisable(PixelVip.java:194) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1592]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1592]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1592]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by FabioZumbi12** [comment]
Try to add `payment` option in your config and in this path to be like this: `configs.database.mysql.transactions.columns.payment` and the value should be `payment`

**Comment by newbie029** [comment]
Its work, can you fix it on the next release please?
also what about useSSL=false things?

**Comment by FabioZumbi12** [comment]
You can try, i dont know if will work but probally yes. You issue wax fixed on latest dev build.
