### ISSUE TITLE
Erro ao usar o comando /addvip

### ISSUE THREAD

**Issue by bravoso** [FabioZumbi12/PixelVip#36]
Ao digitar o comando /darvip ou seus aliases esse erro ocorre, independente de qual grupo vip eu escolha;

`[02:08:57] [Server thread/INFO] [nucleus]: Server ran the command: /addvip Aware vip2 30
[02:08:57] [Server thread/INFO] [minecraft/DedicatedServer]: Error occurred while executing command: null
[02:08:57] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'addvip Aware vip2 30' for source DedicatedServer: null
java.lang.NullPointerException: null
at br.net.fabiozumbi12.pixelvip.sponge.PVConfig.activateVip(PVConfig.java:289) ~[PVConfig.class:?]
at br.net.fabiozumbi12.pixelvip.sponge.cmds.PVCommands.lambda$addVip$12(PVCommands.java:406) ~[PVCommands.class:?]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.1.7-RC3924]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:343) ~[SimpleDispatcher.class:1.12.2-2838-7.1.7-RC3924]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:336) [SpongeCommandManager.class:1.12.2-2838-7.1.7-RC3924]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433) [nz.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Preciso de ajuda com isso, obrigado!

**Comment by FabioZumbi12** [comment]
Ainda acontece usando as ultimas dev builds?

`Não estarei mais suportando as versões de sponge`
