### ISSUE TITLE
Error after restart and warning flood when player get offline

### ISSUE THREAD

**Issue by Crellsin** [FabioZumbi12/PixelVip#42]
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
Versao 1.14.4

Esse erro apos o player com vip ativado ficar offline
[12:55:40] [Server thread/WARN]: [PixelVip] Task #61 for PixelVip v3.0.0 generated an exception
java.lang.RuntimeException: The operation to load user data for '199b1896-0708-3ded-ad65-6b6e962e18fd' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load data for offline players from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:160) ~[?:?]
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetGroups(LuckPermsVaultPermission.java:246) ~[?:?]
at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPlayerGroups(AbstractVaultPermission.java:360) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.PermsAPI.getGroups(PermsAPI.java:34) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.lambda$null$0(PixelVip.java:207) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.lambda$null$1(PixelVip.java:205) ~[?:?]
at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_212]
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.lambda$reloadVipTask$2(PixelVip.java:203) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [server.jar:git-Spigot-cbd1a1b-009d8af]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

e esse erro apos modificar o tipo da database de "file" para "mysql"
ou modificar e fazer reload do plugin tudo ocorre normalmente mas apos reiniciar aconece isso 

[16:10:15] [Server thread/ERROR]: Error occurred while enabling PixelVip v3.0.0 (Is it up to date?)
java.lang.NullPointerException: null
at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.<init>(PVDataMysql.java:48) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.reloadVips(PVConfig.java:355) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.<init>(PVConfig.java:265) ~[?:?]
at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.onEnable(PixelVip.java:119) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [server.jar:git-Spigot-cbd1a1b-009d8af]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by FabioZumbi12** [comment]
This is NOT a bug.
É um alerta do LuckPerms apenas. Desativa essa opção nele que essa mensagem some.
