### ISSUE TITLE
[BUG] Error spam after /pixelvip reload

### ISSUE THREAD

**Issue by Nety01** [FabioZumbi12/PixelVip#47]
**Describe the bug**
After typing /pixelvip reload the console is spammed with these errors and plugin is not responding to any commands
`[22:55:41] [Craft Scheduler Thread - 2150/INFO]: Pixelvip reloaded with success!
[22:55:41] [Craft Scheduler Thread - 2150/WARN]: [PixelVip] Plugin PixelVip v3.0.1 generated an exception while executing task 1460558
java.lang.NullPointerException: null
	at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.getVipList(PVConfig.java:924) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.reloadCmd(PixelVip.java:90) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.mainCommand(PVCommands.java:404) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.lambda$onCommand$3(PVCommands.java:189) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-332]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

**To Reproduce**
1. Type /pixelvip reload

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.15.2
 - Plugin Version: 3.0.1
 - Java Version: Java SE 8u112

**Comment by Nety01** [comment]
Fixed in last version
