### ISSUE TITLE
[BUG] This error message appeared after I enabled the mysql connection in the configuration file.

### ISSUE THREAD

**Issue by chencu5958** [FabioZumbi12/PixelVip#58]
[22:23:09] [Server thread/INFO]: [PixelVip] Enabling PixelVip v3.0.3
[22:23:09] [Server thread/INFO]: [PixelVip] Init config module...[m
[22:23:09] [Server thread/ERROR]: Error occurred while enabling PixelVip v3.0.3 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method "br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.<init>(Lbr/net/fabiozumbi12/pixelvip/bukkit/PixelVip;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, br/net/fabiozumbi12/pixelvip/bukkit/config/PVConfig, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, br/net/fabiozumbi12/pixelvip/bukkit/db/PVDataMysql, have different Class objects for the type br/net/fabiozumbi12/pixelvip/bukkit/PixelVip used in the signature
	at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.reloadVips(PVConfig.java:352) ~[?:?]
	at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.onEnable(PixelVip.java:126) ~[?:?]

**Comment by FabioZumbi12** [comment]
Should be fixed on latest dev builds http://host.areaz12server.net.br:8081/job/PixelVip/lastBuild/
