### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by bertek41** [FabioZumbi12/PixelVip#6]
Spigot 1.8.8 Java 8 Errors:
`[18:01:20 WARN]: [PixelVip] Task #411 for PixelVip v1.0.4 generated an exception
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_101]
at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[?:1.8.0_101]
at java.util.Arrays.asList(Arrays.java:3800) ~[?:1.8.0_101]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.lambda$null$0(PixelVip.java:141) ~[PixelVip-1.0.4-b73.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_101]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.lambda$run$1(PixelVip.java:139) ~[PixelVip-1.0.4-b73.jar:?]
at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_101]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.run(PixelVip.java:137) ~[PixelVip-1.0.4-b73.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:02:20 WARN]: [PixelVip] Task #411 for PixelVip v1.0.4 generated an exception
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_101]
at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[?:1.8.0_101]
at java.util.Arrays.asList(Arrays.java:3800) ~[?:1.8.0_101]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.lambda$null$0(PixelVip.java:141) ~[PixelVip-1.0.4-b73.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_101]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.lambda$run$1(PixelVip.java:139) ~[PixelVip-1.0.4-b73.jar:?]
at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_101]
at br.net.fabiozumbi12.PixelVip.PixelVip$1.run(PixelVip.java:137) ~[PixelVip-1.0.4-b73.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]`

**Comment by FabioZumbi12** [comment]
Check if is fixed on http://areaz12server.net.br:8080/job/PixelVip/

**Comment by bertek41** [comment]
Yes fixed thanks
