### ISSUE TITLE
Please add support to 1.20.4

### ISSUE THREAD

**Issue by Therealalex1s** [FabioZumbi12/PixelVip#70]
Please update the plugin for 1.20.4, maybe you could fix some known bugs too :) I really like this plugin and it would be a shame if it stopped working :(

**Comment by FabioZumbi12** [comment]
As i know, this plugin is not version dependent! Whats the bugs or problems?

**Comment by Therealalex1s** [comment]
I know 1 problem, I can't connect the plugin to database, when I connected it, it created a big mess in console and wasn't even working properly or it would just nor start the plugin. 
I was using plugin version PixelVip-3.0.5-b86-Universal.jar 
and 1.20.4 Paper-497

**Comment by FabioZumbi12** [comment]
You have the error logs?

**Comment by Therealalex1s** [comment]
Well I wanted to send you logs but I don't see the error anymore in the console. Don't know what happened :D But I appreciate the update you released thank you for that :)
Maybe in the future update you could add more placeholders, like: %pixelvip_expiration_desc_short% It would show just Days and hours, %pixelvip_last_active_vip% that would show the last vip rank you owned

And I found 1 bug, when I use %pixelvip_expiration_desc% in BeastTokens menu it shows this error in console and the plugim (BeastTokens) stops working.

Error:
[02:10:15 ERROR]: Could not pass event InventoryClickEvent to BeastTokens v3.14.6
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "puuid" is null
        at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.getVipInfo(PVDataMysql.java:481) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.getVipInfo(PVConfig.java:974) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.getActiveVipInfo(PVConfig.java:993) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.PixelPHAPI.onRequest(PixelPHAPI.java:17) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.mraxetv.beasttokens.utils.Utils.setPlaceholders(Utils.java:212) ~[BeastTokens-3.14.6.jar:?]
        at me.mraxetv.beasttokens.utils.Utils.showInventory(Utils.java:353) ~[BeastTokens-3.14.6.jar:?]
        at me.mraxetv.beasttokens.utils.BTCraftPlayer.openShop(BTCraftPlayer.java:100) ~[BeastTokens-3.14.6.jar:?]
        at me.mraxetv.beasttokens.listener.ShopClickListener.onClick(ShopClickListener.java:126) ~[BeastTokens-3.14.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor754.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3119) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Therealalex1s** [comment]
Update, %pixelvip_expiration_desc% <-- this placeholder isn't working anymore, not even if I try to do /papi parse <name> %pixelvip_expiration_desc% 

It just shows this error: 

[02:13:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-497]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1557) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "puuid" is null
        at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.getVipInfo(PVDataMysql.java:481) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.getVipInfo(PVConfig.java:974) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.getActiveVipInfo(PVConfig.java:993) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.PixelPHAPI.onRequest(PixelPHAPI.java:17) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

**Comment by Therealalex1s** [comment]
And here is another error in console when removing player vip

[02:30:22 INFO]: [PixelVip] Error on removeVip: Cannot invoke "String.split(String)" because "key[2]" is null
[02:30:22 WARN]: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "key[2]" is null
[02:30:22 WARN]:        at PixelVip-3.0.5-b89-Universal.jar//br.net.fabiozumbi12.pixelvip.bukkit.config.PVConfig.removeVip(PVConfig.java:813)
[02:30:22 WARN]:        at PixelVip-3.0.5-b89-Universal.jar//br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.removeVip(PVCommands.java:864)
[02:30:22 WARN]:        at PixelVip-3.0.5-b89-Universal.jar//br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.lambda$onCommand$3(PVCommands.java:177)
[02:30:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[02:30:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:30:22 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:30:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:30:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:30:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[02:30:22 INFO]: [LP] Command not recognised.

**Comment by Therealalex1s** [comment]
Last error I found ( You could fix this one <3 )

[15:50:25 WARN]: [PixelVip] Task #60347 for PixelVip v3.0.5 generated an exception
me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.
LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for 'a01082ae-8547-3495-bbf8-7a738103b81e' (an offline player) from the database
Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:153) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userAddPermission(LuckPermsVaultPermission.java:183) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userAddGroup(LuckPermsVaultPermission.java:243) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerAddGroup(AbstractVaultPermission.java:360) ~[?:?]
        at br.net.fabiozumbi12.pixelvip.bukkit.PermsAPI.lambda$addGroup$1(PermsAPI.java:50) ~[PixelVip-3.0.5-b89-Universal.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Therealalex1s** [comment]
As I'm only server technician I don't think I can experiment with plugins.
But I will appreciate if you fix at least the last error, I change the database from mysql to file.

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/PixelVip/commit/b79ab65b3ddaeabfd6c281c5a59f5e9788a06e2b
