### ISSUE TITLE
[BUG] Problem when starting on proxy server - plugin won't load at all

### ISSUE THREAD

**Issue by TheJoshue** [FabioZumbi12/PixelVip#72]
**Before open an issue, checkout this steps:**
[x] If you are running the plugin at first time, try to run again to see if the problem persists.
[x] Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/PixelVip>
[x] Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
The plugin won't load when put on bungeecord

**To Reproduce**
1. Add PixelVip to your proxy (Bungee) server
2. Start proxy server
3. See logs

**Expected behavior**
It should work

**Screenshots and LOGs**
```
[04:23:29] [main/WARN]: Error loading plugin PixelVip
java.lang.NoClassDefFoundError: org/bukkit/event/Listener
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[Waterfall.jar]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[Waterfall.jar]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall.jar]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Waterfall.jar]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:342) ~[Waterfall.jar]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295) ~[Waterfall.jar]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[Waterfall.jar]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.Listener
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[Waterfall.jar]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall.jar]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 13 more
```

**Server and plugins versions (please complete the following information):**
 - Server: Waterfall 1.21 Build #593
 - Plugin Version: PixelVip-3.1.0-b93-Universal (from jenkins server)
 - Java Version: Java17

**Additional context**
it seems that bungee platform is missing?

**Comment by TheJoshue** [comment]
@FabioZumbi12 just let know when devbuild with fix is pushed so we test, thanks.
